name: Java CI with Maven test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Set up Maven
      uses: vishnubob/wait-for-it@master
      with:
        command: |
          sudo apt-get update
          sudo apt-get install -y maven

    - name: Set up ChromeDriver
      uses: webdriverio/github-action-chromedriver@v1.0
      with:
        chromedriver-version: 96.0.4664.45

    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install google-chrome-stable -y

    - name: Install Selenium
      run: |
        mvn dependency:get -Dartifact=org.seleniumhq.selenium:selenium-java:3.141.59 -Dtransitive=false

    - name: Run tests and generate Allure report
      run: |
        mvn clean test
        mvn io.qameta.allure:allure-maven:2.10.0:report

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven/index.html

    - name: Stop Selenium server
      run: curl -X POST http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
