name: Java CI with Maven test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install Maven
      run: sudo apt-get install maven -y
      
    - name: Install Chrome
      run:  |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get install -f
        google-chrome-stable --version
        
    - name: Start Selenium server
      run: |
        nohup Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99
        wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
        nohup java -jar selenium-server-standalone-3.141.59.jar > /dev/null 2>&1 &

    - name: Run tests and generate Allure report
      run: |
        mvn clean test
        mvn io.qameta.allure:allure-maven:2.10.0:report

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven/index.html

    - name: Stop Selenium server
      run: curl -X POST http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
