name: Java CI with Maven test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install Maven
      run: sudo apt-get install maven -y
            
    - name: Setup Chrome driver
      uses: nanasess/setup-chromedriver@v1
      with:
        chromedriver-version: '93.0.4577.63'

    - name: Run tests and generate Allure report
      run: |
        mvn clean test
        mvn io.qameta.allure:allure-maven:2.10.0:report

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven/index.html

    - name: Stop Selenium server
      run: curl -X POST http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
